---
- name: Copy the postgresql exporter systemd service file
  template:
    src: postgresql_exporter.service.j2
    dest: /etc/systemd/system/postgresql_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart postgresql_exporter
