---
- import_tasks: preflight.yml
  tags:
    - postgresql_exporter_install
    - postgresql_exporter_configure
    - postgresql_exporter_run

- import_tasks: install.yml
  become: true
  tags:
    - postgresql_exporter_install

- import_tasks: configure.yml
  become: true
  tags:
    - postgresql_exporter_configure

- name: Ensure postgresql_exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: postgresql_exporter
    enabled: true
    state: started
  tags:
    - postgresql_exporter_run
